feat: Added aws_wafv2_web_acl rule
carbonetes/brainiac pull request #156
Opened 2023-07-06 09:37 UTC by RamUseMemory1999

2023-07-06 10:43 UTC, jaysonsantos05 requested changes

2023-07-06 10:43 UTC, jaysonsantos05 commented on internal/checker/terraform/rules/aws/aws_wafv2_web_acl_prevention_of_message_lookup_in_log4j2_by_waf.rego
> +    resource.Blocks[_].Blocks[_].Type == "override_action"
I think you should add checking first if resource.Blocks[_].Type == "rule" 
please verify if correct

2023-07-07 03:43 UTC, jaysonsantos05 approved these changes

2023-07-07 07:34 UTC, rommuellropen approved these changes

2023-07-10 04:35 UTC, merged