feat: Added rules for aws_security_group, aws_security_group_rule, an…
carbonetes/brainiac pull request #231
Opened 2023-07-25 07:41 UTC by RamUseMemory1999

…d aws_vpc_security_group_ingress_rule

2023-07-26 00:33 UTC, jaysonsantos05 requested changes

2023-07-26 00:33 UTC, jaysonsantos05 commented on internal/checker/terraform/rules/aws/aws_security_group_no_security_groups_allow_ingress.rego
> +    toPort == -1
please confirm if toPort is really need to check

2023-07-26 02:32 UTC, jaysonsantos05 approved these changes

2023-07-27 03:38 UTC, rommuellropen approved these changes

2023-07-27 03:39 UTC, merged