feat: Added aws_redshiftserverless_namespace rule
carbonetes/brainiac pull request #244
Opened 2023-07-26 09:37 UTC by RamUseMemory1999

2023-07-26 14:05 UTC, jaysonsantos05 approved these changes

2023-07-27 03:48 UTC, rommuellropen requested changes

2023-07-27 03:48 UTC, rommuellropen commented on internal/checker/terraform/rules/aws/aws_redshiftserverless_namespace_redshiftserverless_namespace_encrypted_by_kms_utilizing_cmk.rego
> +# - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_ontap_file_system
@RamUseMemory1999 kindly verify if the link for related sources matched the resource

2023-07-27 03:56 UTC, rommuellropen approved these changes

2023-07-27 03:56 UTC, merged