feat: Added rules for aws_alb, aws_elb, and aws_lb
carbonetes/brainiac pull request #277
Opened 2023-08-03 09:22 UTC by sambuenaventuracarbo

2023-08-03 09:29 UTC, jaysonsantos05 requested changes

2023-08-03 09:29 UTC, jaysonsantos05 commented on internal/checker/terraform/rules/aws/verify_alb_desync_mode.rego.rego
> +}
remove line 32-34 replace with
block.Attributes.routing_http_desync_mitigation_mode != "monitor"

2023-08-03 09:44 UTC, RamUseMemory1999 approved these changes

2023-08-03 09:48 UTC, jaysonsantos05 approved these changes

2023-08-04 01:01 UTC, rommuellropen approved these changes

2023-08-04 01:01 UTC, merged