feat: Added aws_efs_access_point rule
carbonetes/brainiac pull request #281
Opened 2023-08-04 05:33 UTC by sambuenaventuracarbo

2023-08-04 05:42 UTC, jaysonsantos05 requested changes

2023-08-04 05:42 UTC, jaysonsantos05 commented on internal/checker/terraform/rules/aws/verify_efs_access_point_root.rego
> +	block.Blocks[_].Attributes.path != "/"
add checking above line 30 
block.Blocks[_].Type == "root_directory"

2023-08-04 05:57 UTC, RamUseMemory1999 approved these changes

2023-08-04 08:09 UTC, jaysonsantos05 approved these changes

2023-08-07 01:45 UTC, rommuellropen approved these changes

2023-08-07 01:45 UTC, merged