feat: implement rule Verify that Azure Kubernetes Cluster (AKS) nodes are configured to use scale sets
carbonetes/brainiac pull request #532
Opened 2023-10-06 01:28 UTC by sairen-carbonetes

2023-10-06 03:55 UTC, jaysonsantos05 requested changes

2023-10-06 03:55 UTC, jaysonsantos05 commented on internal/checker/terraform/rules/azure/azurerm_kubernetes_cluster_pooltype_is_scale_set.rego
> +	some resource in input
remove unused or not related code block

2023-10-06 04:19 UTC, sairen-carbonetes commented on internal/checker/terraform/rules/azure/azurerm_kubernetes_cluster_pooltype_is_scale_set.rego
> +	some resource in input
Noted on this. Thank you!

2023-10-09 01:20 UTC, jaysonsantos05 approved these changes

2023-10-09 01:21 UTC, merged