feat: Implement rule for verifying that containers with the NET_RAW c…
carbonetes/brainiac pull request #873
Opened 2023-12-19 02:26 UTC by RamUseMemory1999

…apability are not admitted

2023-12-22 07:09 UTC, sairen-carbonetes approved these changes

2023-12-22 07:36 UTC, sairen-carbonetes requested changes

2023-12-22 07:36 UTC, sairen-carbonetes commented on internal/checker/terraform/rules/kubernetes/kubernetes_pod_security_policy_containers_net_raw_restricted.rego
> +	some capabalities in inner_block.Attributes.required_drop_capabilities
Minor Adjustment: capabilities -> capabilities

2023-12-27 01:11 UTC, jaysonsantos05 approved these changes

2023-12-27 01:11 UTC, merged