feat: Implement rule for verifying that Image Tag should be fixed - n…
carbonetes/brainiac pull request #888
Opened 2023-12-20 07:55 UTC by RamUseMemory1999

…ot latest or blank

2023-12-22 07:27 UTC, sairen-carbonetes approved these changes

2023-12-26 23:51 UTC, jaysonsantos05 requested changes

2023-12-26 23:51 UTC, jaysonsantos05 commented on internal/checker/terraform/rules/kubernetes/kubernetes_deployment_fixed_image_tag.rego
> +	endswith(container_block.Attributes.image, ":")
this should be not contains since no tag is set is automatically latest

2023-12-27 01:10 UTC, jaysonsantos05 approved these changes

2023-12-27 01:10 UTC, merged