feat: Added aws_db_instance rule
carbonetes/brainiac pull request #90
Opened 2023-06-22 03:30 UTC by RamUseMemory1999

2023-06-22 04:25 UTC, jaysonsantos05 requested changes

2023-06-22 04:25 UTC, jaysonsantos05 commented on internal/checker/terraform/rules/aws/aws_db_instance_rds_database_iam_authentication_enabled.rego
> +    has_attribute(resource.Attributes, "engine")
remove this line since it is already included in isvalid (line 38)

2023-06-22 08:08 UTC, jaysonsantos05 approved these changes

2023-06-23 03:17 UTC, rommuellropen approved these changes

2023-06-23 03:17 UTC, merged